name: Automated Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
    
    - name: Run tests
      run: make test
    
    - name: Build for multiple platforms
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o dotman-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o dotman-linux-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -o dotman-windows-amd64.exe .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -o dotman-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o dotman-darwin-arm64 .
    
    - name: Create checksums
      run: |
        sha256sum dotman-linux-amd64 > checksums.txt
        sha256sum dotman-linux-arm64 >> checksums.txt
        sha256sum dotman-windows-amd64.exe >> checksums.txt
        sha256sum dotman-darwin-amd64 >> checksums.txt
        sha256sum dotman-darwin-arm64 >> checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dotman-linux-amd64
          dotman-linux-arm64
          dotman-windows-amd64.exe
          dotman-darwin-amd64
          dotman-darwin-arm64
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## Installation
          
          ### Linux
          ```bash
          # AMD64
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/dotman-linux-amd64
          chmod +x dotman-linux-amd64
          sudo mv dotman-linux-amd64 /usr/local/bin/dotman
          
          # ARM64
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/dotman-linux-arm64
          chmod +x dotman-linux-arm64
          sudo mv dotman-linux-arm64 /usr/local/bin/dotman
          ```
          
          ### macOS
          ```bash
          # Intel
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/dotman-darwin-amd64 -o dotman
          chmod +x dotman
          sudo mv dotman /usr/local/bin/dotman
          
          # Apple Silicon
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/dotman-darwin-arm64 -o dotman
          chmod +x dotman
          sudo mv dotman /usr/local/bin/dotman
          ```
          
          ### Windows
          Download `dotman-windows-amd64.exe` and rename it to `dotman.exe`
          
          ## Verification
          Verify the checksums:
          ```bash
          sha256sum -c checksums.txt
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
